name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "48 0 * * *"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Get coverage
        shell: bash
        run: |
          : Get coverage
          git checkout --orphan=pages
          git checkout main -- index.html
          for a in $(
            git ls-remote . |
            perl -ne '
              next unless s,.*/(ref-),$1,;
              print;
            '
          ); do
            export event=$(echo "$a" | perl -pe 's/ref-(.*?)-.*/$1/')
            export ref=$(echo "$a" | perl -pe 's/.*-//')
            git checkout origin/$a -- "$event/$ref" || true
            echo "$event" >> /tmp/events
          done
          set -x
          for event in $(sort -u /tmp/events); do
            export event
            if ! grep -q "$event" index.html; then
              perl -pi -e 's#^(\s+)(</ul>)#$1  <li><a href="$ENV{event}/">$ENV{event}</a></li>\n$1$2#' index.html
            fi
            (
              cd "$event";
              find . -mindepth 1 -maxdepth 1 -type d -print0
            ) | perl -e '
            $/="\0";
            my $event=$ENV{event};

            print qq{<html>
            <head><title>check-spelling coverage for $event</title>
            <style>
            body {
              font-family: sans-serif;
            }
            </style></head>
            <body>
              <h1>check-spelling coverage for $event</h1>
              <ul>
            };
            my %list;
            for my $ref (<>) {
              chomp $ref;
              $ref =~ s!.*/!!;
              my $date=`git log -1 "origin/ref-$event-$ref" --pretty="%ai"`;
              chomp $date;
              my $key="$date ($ref)";
              my $entry=qq{<a href="$ref/">$key</a>};
              $list{$key} = $entry;
            }
            for my $key (sort keys %list) {
              print "    <li>$list{$key}</li>\n";
            }
            print qq{  </ul>
            </body>
            };
            ' > $event/index.html
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
